# Generated by Django 4.1.5 on 2023-01-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("denom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, unique=True)),
                ("phone_number", models.PositiveIntegerField(unique=True)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("message", models.TextField(max_length=1000)),
            ],
        ),
    ]
