# Generated by Django 4.1.5 on 2023-01-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("denom", "0003_alter_contact_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcriber",
            name="date_subscribed",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(max_length=1000),
        ),
    ]
